### ISSUE TITLE
Unable to load with laravel mix and webpack

### ISSUE THREAD

**Issue by mohamadreza89** [creativetimofficial/vue-material-kit#1]
I'm using laravel-mix as my environment and I want to use the vue-material-kit.
Current I can't  load it because of some errors and I have no idea how to fix them
Is there any chance that I compile this package with my other components in laravel-mix ?

**Comment by dragosct10** [comment]
Hi, @mohamadreza89! Thank you for using our products. Unfortunately, we don't work with laravel, but you tried their [docs](https://laravel.com/docs/5.7/mix) to see if it works? 

Regards, 
Dragos

**Comment by japrehm** [comment]
@mohamadreza89  
I forked the theme, and added it to laravel. 

https://github.com/japrehm/laravel-vue-material-kit

**Comment by Rinmawia** [comment]
> @mohamadreza89
> I forked the theme, and added it to laravel.
> 
> https://github.com/japrehm/laravel-vue-material-kit

Thanks a lot, but i have one question... will the app break if i upgrade to laravel version 6
