### ISSUE TITLE
 Expected ";" when using laravel mixing. 

### ISSUE THREAD

**Issue by danjob** [creativetimofficial/vue-material-kit#2]
https://github.com/creativetimofficial/vue-material-kit/blob/7b4e77fc392a98a1b85990e42ab65dacfdd4f8df/src/assets/scss/material-kit/_mixins.scss#L15

**Comment by dragosct10** [comment]
Hi, @danjob! Thank you for using our products. Yes, you are right we will fix it in the next update. 

Regards, 
Dragos
