### ISSUE TITLE
[Feature Request] How to.

### ISSUE THREAD

**Issue by uwejan** [creativetimofficial/vue-material-kit#6]
### What is your enhancement?
Hi, i appreciate a little guide on how to use this package with brand new vue app. many thanks.
Edit: on already exisiting project, using laravel and vue only views.

**Comment by dragosct10** [comment]
Hi, @uwejan! Thank you for using our products. From what I noticed you want to integrate vue material kit with laravel, right? 

Regards,
Dragos

**Comment by uwejan** [comment]
@dragosct10 yes, i know you have laravel version, but i wish to use vue version, but have not figured out how to.

**Comment by dragosct10** [comment]
Hi, @uwejan! Yes, we have the laravel version, but we don't have yet the vue with laravel version. For the moment I can only give you this video to help you https://www.youtube.com/watch?v=3nLdc0NBiH8&t=8s. 

Regards,
Dragos
